version: '3'
services:

  postgres:
    image: mdillon/postgis
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres


  waiter:
    image: jwilder/dockerize
    command: |
      dockerize -wait tcp://postgres:5432
                -wait-retry-interval 5s
                -timeout 5m

  ibis:
    image: ibis:${PYTHON_VERSION:-3.6}
    env_file:
      - ./.env
    volumes:
      - /tmp/ibis:/tmp
      - ..:/ibis
    build:
      context: ..
      dockerfile: ci/Dockerfile.dev
      args:
        PYTHON: ${PYTHON_VERSION:-3.6}

  ibis-docs:
    image: ibis-docs:${PYTHON_VERSION:-3.6}
    env_file:
      - ./.env
    volumes:
      - /tmp/ibis:/tmp
      - ..:/ibis
    build:
      context: ..
      dockerfile: ci/Dockerfile.docs
      args:
        PYTHON: ${PYTHON_VERSION:-3.6}
